//! Packet builder over a caller-owned buffer.
//!
//! Size rules (RFC 6762 section 17, plan section 4.5): the DNS payload has
//! a soft target of 1472 octets over IPv4 and 1452 over IPv6 (one Ethernet
//! frame), and a hard cap of 8972 / 8952 (the 9000-octet limit includes
//! the IP and UDP headers). One record may exceed the soft target up to the
//! hard cap when it is the first record in the packet; a later record that
//! does not fit under the soft target returns `error.NoSpace` and the
//! builder is left unchanged, so the caller can `finish` and start the next
//! packet.
//!
//! Compression (RFC 1035 section 4.1.4) is applied to owner names and to
//! the names inside PTR, SRV and NSEC rdata, which RFC 6762 section 18.14
//! allows. A pointer is only ever written to a prior occurrence with the
//! same bytes (ASCII case included), so the uncompressed rdata a peer
//! reconstructs is byte-for-byte the `Name` the caller passed in. RFC 6762
//! section 8.2 compares "raw uncompressed rdata" octet by octet, and this
//! rule lets the responder compare its local record values against a
//! peer's packet without first parsing back its own probe. (mDNSResponder
//! matches suffixes case-insensitively; the loss in compression when a
//! caller mixes case is a few octets, and the decoder still accepts such
//! pointers from peers.)
//!
//! In `legacy` mode (a unicast reply to a legacy query, RFC 6762 section
//! 6.7, "a conventional unicast response as would be generated by a
//! conventional Unicast DNS server") the SRV target is never compressed
//! (section 18.14), the NSEC next-domain name is never compressed (RFC
//! 4034 section 4.1.1), TTLs are capped at 10 s and the cache-flush bit is
//! cleared.
const std = @import("std");
const name_mod = @import("name.zig");
const message = @import("message.zig");
const rdata_mod = @import("rdata.zig");
const txt_mod = @import("txt.zig");

pub const Name = name_mod.Name;
pub const Header = message.Header;
pub const RType = message.RType;
pub const Section = message.Section;
pub const Srv = rdata_mod.Srv;
pub const Nsec = rdata_mod.Nsec;
pub const Hinfo = rdata_mod.Hinfo;

pub const Family = enum(u8) { v4, v6 };

/// Soft payload target: 1500 - 20 (IPv4) - 8 (UDP).
pub const soft_limit_v4 = 1472;
/// Soft payload target: 1500 - 40 (IPv6) - 8 (UDP).
pub const soft_limit_v6 = 1452;
/// Hard payload cap: 9000 - 20 - 8 (RFC 6762 section 17).
pub const hard_limit_v4 = 8972;
/// Hard payload cap: 9000 - 40 - 8 (RFC 6762 section 17).
pub const hard_limit_v6 = 8952;
/// RFC 6762 section 6.7: TTLs in a legacy unicast response.
pub const legacy_ttl_cap_s: u32 = 10;
/// Compression table size. When full, later names are written without
/// compression; nothing fails.
pub const max_compression_entries = 128;
/// A compression pointer holds a 14-bit offset.
const max_pointer_offset = 0x3FFF;

pub fn softLimit(f: Family) usize {
    return switch (f) {
        .v4 => soft_limit_v4,
        .v6 => soft_limit_v6,
    };
}

pub fn hardLimit(f: Family) usize {
    return switch (f) {
        .v4 => hard_limit_v4,
        .v6 => hard_limit_v6,
    };
}

pub const Options = struct {
    family: Family = .v4,
    /// RFC 6762 section 6.7 unicast reply to a legacy query.
    legacy: bool = false,
    /// Override the per-family soft target (tests, or a known path MTU).
    soft_limit: ?usize = null,
    /// Lower the per-family hard cap. Never raised above the buffer or
    /// above the RFC 6762 section 17 cap for the family (8972 / 8952).
    hard_limit: ?usize = null,
};

/// Record data for `addRR`. Name-bearing variants are compressed against
/// the packet; `raw` is copied as given.
pub const Rdata = union(enum) {
    raw: []const u8,
    a: [4]u8,
    aaaa: [16]u8,
    ptr: Name,
    srv: Srv,
    /// Wire TXT rdata, e.g. `Txt.slice()`. Must be a valid sequence of
    /// length-prefixed strings (`error.InvalidTxt` otherwise); an empty
    /// slice is written as the single zero octet RFC 6763 section 6.1
    /// requires ("DNS-SD implementations MUST NOT emit empty TXT
    /// records"). The 400-octet bound of plan section 4.5 is enforced by
    /// `Txt`, not here, so captured records of any size can be re-emitted.
    txt: []const u8,
    nsec: Nsec,
    hinfo: Hinfo,
};

pub const Error = error{
    /// The item does not fit under the applicable limit. The builder is
    /// unchanged.
    NoSpace,
    /// A question after a record, or a record in a section that precedes
    /// one already written. The builder is unchanged.
    SectionOrder,
    /// An HINFO string over 255 octets.
    StringTooLong,
    /// `Rdata.txt` bytes are not a sequence of length-prefixed strings.
    InvalidTxt,
};

pub const Builder = struct {
    buf: []u8,
    len: usize,
    soft_limit: usize,
    hard_limit: usize,
    legacy: bool,
    header: Header,
    /// Highest section that holds a record, or null while only questions
    /// have been written.
    last_section: ?Section,
    rr_count: usize,
    comp: [max_compression_entries]u16,
    comp_len: usize,

    /// `buf` must hold at least a header (12 octets); that is a caller
    /// contract, not a packet condition, hence the assert.
    pub fn init(buf: []u8, opts: Options) Builder {
        std.debug.assert(buf.len >= Header.len);
        // An override can only lower the cap: RFC 6762 section 17 bounds
        // the whole datagram at 9000 octets including IP and UDP headers.
        const hard = @min(@min(opts.hard_limit orelse hardLimit(opts.family), hardLimit(opts.family)), buf.len);
        const soft = @min(opts.soft_limit orelse softLimit(opts.family), hard);
        return .{
            .buf = buf,
            .len = Header.len,
            .soft_limit = soft,
            .hard_limit = hard,
            .legacy = opts.legacy,
            .header = .{},
            .last_section = null,
            .rr_count = 0,
            .comp = undefined,
            .comp_len = 0,
        };
    }

    /// Start a new packet in the same buffer. Keeps the id and flags.
    pub fn reset(b: *Builder) void {
        b.len = Header.len;
        b.header.qdcount = 0;
        b.header.ancount = 0;
        b.header.nscount = 0;
        b.header.arcount = 0;
        b.last_section = null;
        b.rr_count = 0;
        b.comp_len = 0;
    }

    pub fn setId(b: *Builder, id: u16) void {
        b.header.id = id;
    }

    pub fn setFlags(b: *Builder, flags: Header.Flags) void {
        b.header.flags = flags;
    }

    /// QR=1, AA=1 (RFC 6762 section 18.2, 18.4).
    pub fn setResponse(b: *Builder) void {
        b.header.flags.qr = true;
        b.header.flags.aa = true;
    }

    /// TC bit (RFC 6762 section 18.5): more known answers follow.
    pub fn setTruncated(b: *Builder, tc: bool) void {
        b.header.flags.tc = tc;
    }

    /// Payload length so far, header included.
    pub fn payloadLen(b: *const Builder) usize {
        return b.len;
    }

    pub fn recordCount(b: *const Builder) usize {
        return b.rr_count;
    }

    pub fn questionCount(b: *const Builder) usize {
        return b.header.qdcount;
    }

    /// True when nothing but the header has been written.
    pub fn isEmpty(b: *const Builder) bool {
        return b.len == Header.len;
    }

    /// Write the header and return the packet. The builder stays usable.
    pub fn finish(b: *Builder) []const u8 {
        b.header.write(b.buf[0..Header.len]);
        return b.buf[0..b.len];
    }

    pub fn addQuestion(b: *Builder, name: Name, qtype: RType, qclass: u16, qu: bool) Error!void {
        if (b.last_section != null) return error.SectionOrder;
        if (b.header.qdcount == std.math.maxInt(u16)) return error.NoSpace;
        const saved = b.save();
        errdefer b.restore(saved);
        // Questions always fit under the soft target.
        try b.writeName(name, true, b.soft_limit);
        try b.writeInt(u16, qtype.toInt(), b.soft_limit);
        const class_wire = (qclass & ~message.qu_bit) | (if (qu) message.qu_bit else 0);
        try b.writeInt(u16, class_wire, b.soft_limit);
        b.header.qdcount += 1;
    }

    /// Append a record. Sections must be written in order (answer,
    /// authority, additional). See the module doc for the size rules.
    pub fn addRR(
        b: *Builder,
        section: Section,
        name: Name,
        rtype: RType,
        class: u16,
        cache_flush: bool,
        ttl: u32,
        rdata: Rdata,
    ) Error!void {
        if (b.last_section) |last| {
            if (@backingInt(section) < @backingInt(last)) return error.SectionOrder;
        }
        if (b.header.count(section) == std.math.maxInt(u16)) return error.NoSpace;
        const limit = if (b.rr_count == 0) b.hard_limit else b.soft_limit;
        const saved = b.save();
        errdefer b.restore(saved);

        try b.writeName(name, true, limit);
        try b.writeInt(u16, rtype.toInt(), limit);
        const flush = cache_flush and !b.legacy;
        const class_wire = (class & ~message.cache_flush_bit) | (if (flush) message.cache_flush_bit else 0);
        try b.writeInt(u16, class_wire, limit);
        const ttl_wire = if (b.legacy) @min(ttl, legacy_ttl_cap_s) else ttl;
        try b.writeInt(u32, ttl_wire, limit);
        const rdlength_at = b.len;
        try b.writeInt(u16, 0, limit);
        const rdata_start = b.len;
        switch (rdata) {
            .raw => |bytes| try b.writeBytes(bytes, limit),
            .a => |addr| try b.writeBytes(&addr, limit),
            .aaaa => |addr| try b.writeBytes(&addr, limit),
            .ptr => |target| try b.writeName(target, true, limit),
            .srv => |srv| {
                try b.writeInt(u16, srv.priority, limit);
                try b.writeInt(u16, srv.weight, limit);
                try b.writeInt(u16, srv.port, limit);
                // RFC 6762 section 18.14: never compress the SRV target in
                // a legacy unicast response.
                try b.writeName(srv.target, !b.legacy, limit);
            },
            .txt => |bytes| {
                (txt_mod.View{ .bytes = bytes }).validate() catch return error.InvalidTxt;
                // RFC 6763 section 6.1: an empty TXT is one zero octet.
                try b.writeBytes(if (bytes.len == 0) &.{0} else bytes, limit);
            },
            .nsec => |nsec| {
                // RFC 4034 section 4.1.1: "A sender MUST NOT use DNS name
                // compression on the Next Domain Name field"; RFC 6762
                // section 6.7 makes a legacy reply a conventional unicast
                // response, so that rule applies there. Multicast replies
                // may compress it (RFC 6762 section 18.14).
                try b.writeName(nsec.next, !b.legacy, limit);
                const wb = nsec.wireBitmap();
                if (wb.len != 0) {
                    try b.writeBytes(&.{ 0, @intCast(wb.len) }, limit);
                    try b.writeBytes(wb.buf[0..wb.len], limit);
                }
            },
            .hinfo => |h| {
                if (h.cpu.len > 255 or h.os.len > 255) return error.StringTooLong;
                try b.writeBytes(&.{@intCast(h.cpu.len)}, limit);
                try b.writeBytes(h.cpu, limit);
                try b.writeBytes(&.{@intCast(h.os.len)}, limit);
                try b.writeBytes(h.os, limit);
            },
        }
        const rdlength = b.len - rdata_start;
        if (rdlength > std.math.maxInt(u16)) return error.NoSpace;
        std.mem.writeInt(u16, b.buf[rdlength_at..][0..2], @intCast(rdlength), .big);

        switch (section) {
            .answer => b.header.ancount += 1,
            .authority => b.header.nscount += 1,
            .additional => b.header.arcount += 1,
        }
        b.last_section = section;
        b.rr_count += 1;
    }

    // -- internals ---------------------------------------------------------

    const Saved = struct { len: usize, comp_len: usize };

    fn save(b: *const Builder) Saved {
        return .{ .len = b.len, .comp_len = b.comp_len };
    }

    fn restore(b: *Builder, s: Saved) void {
        b.len = s.len;
        b.comp_len = s.comp_len;
    }

    fn writeBytes(b: *Builder, bytes: []const u8, limit: usize) error{NoSpace}!void {
        if (b.len + bytes.len > limit) return error.NoSpace;
        @memcpy(b.buf[b.len..][0..bytes.len], bytes);
        b.len += bytes.len;
    }

    fn writeInt(b: *Builder, comptime T: type, v: T, limit: usize) error{NoSpace}!void {
        const n = @divExact(@typeInfo(T).int.bits, 8);
        if (b.len + n > limit) return error.NoSpace;
        std.mem.writeInt(T, b.buf[b.len..][0..n], v, .big);
        b.len += n;
    }

    /// Write `name`, replacing the longest suffix already in the packet by
    /// a pointer when `compress` is set. Every label written in full is
    /// added to the compression table, whatever `compress` says.
    fn writeName(b: *Builder, name: Name, compress: bool, limit: usize) error{NoSpace}!void {
        var it = name.labels();
        // Walk suffixes from the whole name down to the last label.
        while (true) {
            const suffix_start = it.pos;
            if (suffix_start >= name.len - 1) break; // only the root remains
            if (compress) {
                if (b.findSuffix(name.buf[suffix_start..name.len])) |target| {
                    const ptr: u16 = 0xC000 | target;
                    try b.writeInt(u16, ptr, limit);
                    return;
                }
            }
            const label = it.next() orelse break;
            b.addCompressionEntry(b.len);
            try b.writeBytes(&.{@intCast(label.len)}, limit);
            try b.writeBytes(label, limit);
        }
        try b.writeBytes(&.{0}, limit);
    }

    /// Offset of a name already in the packet whose uncompressed bytes
    /// equal the wire-form `suffix` exactly, or null. Exact, not case
    /// folded: see the module doc (RFC 6762 section 8.2 compares the
    /// uncompressed rdata octet by octet, so the bytes a peer reconstructs
    /// must be the bytes the caller passed in).
    fn findSuffix(b: *const Builder, suffix: []const u8) ?u16 {
        const written = b.buf[0..b.len];
        for (b.comp[0..b.comp_len]) |off| {
            const d = Name.decode(written, off) catch continue;
            if (std.mem.eql(u8, d.name.slice(), suffix)) return off;
        }
        return null;
    }

    fn addCompressionEntry(b: *Builder, off: usize) void {
        if (b.comp_len >= max_compression_entries) return;
        if (off > max_pointer_offset) return;
        b.comp[b.comp_len] = @intCast(off);
        b.comp_len += 1;
    }
};

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

const testing = std.testing;
const Message = message.Message;

fn expectName(expected: []const u8, n: Name) !void {
    try name_mod.expectText(expected, n);
}

test "build -> parse round trip with compression" {
    var buf: [1500]u8 = undefined;
    var b = Builder.init(&buf, .{});
    b.setResponse();
    b.setId(0);
    const svc = try Name.parse("_qmsg._udp.local");
    const inst = try Name.parse("Alice._qmsg._udp.local");
    const host = try Name.parse("studio-a.local");
    const txt = try txt_mod.Txt.build(&.{ .{ .key = "v", .value = "1" }, .{ .key = "flag" } });
    var v6: [16]u8 = @splat(0);
    v6[0] = 0xfe;
    v6[15] = 1;
    try b.addRR(.answer, svc, .ptr, message.class_in, false, 4500, .{ .ptr = inst });
    try b.addRR(.answer, inst, .srv, message.class_in, true, 120, .{ .srv = .{ .port = 4433, .target = host } });
    try b.addRR(.answer, inst, .txt, message.class_in, true, 4500, .{ .txt = txt.slice() });
    try b.addRR(.additional, host, .a, message.class_in, true, 120, .{ .a = .{ 10, 0, 0, 1 } });
    try b.addRR(.additional, host, .aaaa, message.class_in, true, 120, .{ .aaaa = v6 });
    try b.addRR(.additional, host, .nsec, message.class_in, true, 120, .{ .nsec = try Nsec.fromTypes(host, &.{ .a, .aaaa }) });
    try b.addRR(.additional, host, .hinfo, message.class_in, false, 120, .{ .hinfo = .{ .cpu = "arm", .os = "macOS" } });
    const pkt = b.finish();

    // Compression made it smaller than the flat sum of the names.
    const flat = 12 + (svc.len + 10 + inst.len) + (inst.len + 10 + 6 + host.len) + (inst.len + 10 + txt.slice().len) +
        (host.len + 10 + 4) + (host.len + 10 + 16) + (host.len + 10 + host.len + 4) + (host.len + 10 + 10);
    try testing.expect(pkt.len < flat);

    const m = try Message.parse(pkt);
    try testing.expect(m.header.flags.qr and m.header.flags.aa and !m.header.flags.tc);
    try testing.expectEqual(@as(u16, 3), m.header.ancount);
    try testing.expectEqual(@as(u16, 4), m.header.arcount);
    try testing.expectEqual(pkt.len, m.end);
    var an = m.answers();
    const r_ptr = an.next().?;
    try testing.expect(r_ptr.name.eql(&svc));
    try testing.expect(!r_ptr.cache_flush);
    try testing.expectEqual(@as(u32, 4500), r_ptr.ttl);
    try expectName("Alice._qmsg._udp.local", try rdata_mod.decodePtr(pkt, r_ptr));
    const r_srv = an.next().?;
    try testing.expect(r_srv.cache_flush);
    const srv = try rdata_mod.decodeSrv(pkt, r_srv);
    try testing.expectEqual(@as(u16, 4433), srv.port);
    try testing.expect(srv.target.eql(&host));
    // The SRV target was compressed (rdata is shorter than the flat form).
    try testing.expect(r_srv.rdata.len < 6 + host.len);
    const r_txt = an.next().?;
    const tv = try rdata_mod.decodeTxt(r_txt);
    try testing.expectEqualStrings("1", tv.get("V").?);
    try testing.expect(tv.has("FLAG"));
    var ar = m.additional();
    try testing.expectEqual([4]u8{ 10, 0, 0, 1 }, try rdata_mod.decodeA(ar.next().?.rdata));
    const got_v6 = try rdata_mod.decodeAaaa(ar.next().?.rdata);
    try testing.expectEqual(v6, got_v6);
    const r_nsec = ar.next().?;
    const nsec = try rdata_mod.decodeNsec(pkt, r_nsec);
    try testing.expect(nsec.next.eql(&host));
    try testing.expect(nsec.has(.a) and nsec.has(.aaaa) and !nsec.has(.srv));
    const h = try rdata_mod.decodeHinfo(ar.next().?);
    try testing.expectEqualStrings("macOS", h.os);
    try testing.expect(ar.next() == null);
}

test "QU and cache-flush bits round trip through the builder" {
    var buf: [512]u8 = undefined;
    var b = Builder.init(&buf, .{});
    const n = try Name.parse("host.local");
    try b.addQuestion(n, .any, message.class_in, true);
    try b.addQuestion(n, .a, message.class_in, false);
    try b.addRR(.answer, n, .a, message.class_in, true, 120, .{ .a = .{ 1, 2, 3, 4 } });
    try b.addRR(.answer, n, .a, message.class_in, false, 120, .{ .a = .{ 1, 2, 3, 5 } });
    const m = try Message.parse(b.finish());
    var qs = m.questions();
    try testing.expect(qs.next().?.qu);
    try testing.expect(!qs.next().?.qu);
    var an = m.answers();
    const r1 = an.next().?;
    try testing.expect(r1.cache_flush);
    try testing.expectEqual(message.class_in, r1.class);
    try testing.expectEqual(@as(u16, 0x8001), r1.class_raw);
    const r2 = an.next().?;
    try testing.expect(!r2.cache_flush);
    try testing.expectEqual(@as(u16, 1), r2.class_raw);
}

test "legacy builder never compresses SRV target" {
    const inst = try Name.parse("Alice._qmsg._udp.local");
    const host = try Name.parse("studio-a.local");
    const srv: Srv = .{ .port = 4433, .target = host };
    const nsec = try Nsec.fromTypes(host, &.{ .a, .srv });

    var flat: [64]u8 = undefined;
    const flat_len = try rdata_mod.encodeSrv(srv, &flat);
    var flat_nsec: [64]u8 = undefined;
    const flat_nsec_len = try rdata_mod.encodeNsec(nsec, &flat_nsec);

    var buf: [512]u8 = undefined;
    for ([_]bool{ false, true }) |legacy| {
        var b = Builder.init(&buf, .{ .legacy = legacy });
        b.setId(0x1234);
        b.setResponse();
        try b.addQuestion(inst, .srv, message.class_in, false);
        // Puts "studio-a.local" in the packet before the SRV so there is
        // something to compress against.
        try b.addRR(.answer, host, .a, message.class_in, true, 120, .{ .a = .{ 10, 0, 0, 1 } });
        try b.addRR(.answer, inst, .srv, message.class_in, true, 120, .{ .srv = srv });
        try b.addRR(.additional, host, .nsec, message.class_in, true, 120, .{ .nsec = nsec });
        const pkt = b.finish();
        const m = try Message.parse(pkt);
        try testing.expectEqual(@as(u16, 0x1234), m.header.id);
        var an = m.answers();
        const r_a = an.next().?;
        const r_srv = an.next().?;
        const decoded = try rdata_mod.decodeSrv(pkt, r_srv);
        try testing.expect(decoded.target.eql(&host));
        try testing.expectEqual(@as(u16, 4433), decoded.port);
        var ar = m.additional();
        const r_nsec = ar.next().?;
        try testing.expect((try rdata_mod.decodeNsec(pkt, r_nsec)).has(.srv));
        if (legacy) {
            try testing.expectEqualSlices(u8, flat[0..flat_len], r_srv.rdata);
            // RFC 4034 section 4.1.1 (via RFC 6762 section 6.7): the NSEC
            // next-domain name is a full uncompressed name in a legacy
            // reply, so the rdata starts with the label, not a pointer.
            try testing.expectEqualSlices(u8, flat_nsec[0..flat_nsec_len], r_nsec.rdata);
            try testing.expectEqual(@as(u8, "studio-a".len), r_nsec.rdata[0]);
            // TTL capped at 10 s and cache-flush cleared (section 6.7).
            try testing.expectEqual(legacy_ttl_cap_s, r_a.ttl);
            try testing.expectEqual(legacy_ttl_cap_s, r_srv.ttl);
            try testing.expect(!r_a.cache_flush and !r_srv.cache_flush);
            // The owner name is still compressed in legacy mode: the SRV
            // record starts right after the A rdata with a 2-octet pointer.
            try testing.expectEqual(r_a.rdata_offset + 4 + 2 + 10, r_srv.rdata_offset);
        } else {
            try testing.expect(r_srv.rdata.len < flat_len);
            // Multicast: the next name is a 2-octet pointer (section 18.14).
            try testing.expectEqual(2 + 2 + nsec.bitmapLen(), r_nsec.rdata.len);
            try testing.expectEqual(@as(u32, 120), r_a.ttl);
            try testing.expect(r_a.cache_flush and r_srv.cache_flush);
        }
    }
}

test "builder writes an empty TXT as a single zero byte" {
    // RFC 6763 section 6.1: "DNS-SD implementations MUST NOT emit empty
    // TXT records." `Txt.fromWire("")` accepts an empty rdata from a peer
    // for interoperability; re-emitting it must still produce one zero
    // octet, the same bytes `Txt.build(&.{})` gives.
    var buf: [256]u8 = undefined;
    var b = Builder.init(&buf, .{});
    const n = try Name.parse("x.local");
    const from_peer = try txt_mod.Txt.fromWire("");
    try testing.expectEqual(@as(usize, 0), from_peer.slice().len);
    try b.addRR(.answer, n, .txt, message.class_in, false, 4500, .{ .txt = from_peer.slice() });
    try b.addRR(.answer, n, .txt, message.class_in, false, 4500, .{ .txt = "" });
    try b.addRR(.answer, n, .txt, message.class_in, false, 4500, .{ .txt = (try txt_mod.Txt.build(&.{})).slice() });
    const pkt = b.finish();
    const m = try Message.parse(pkt);
    var an = m.answers();
    var count: usize = 0;
    while (an.next()) |r| : (count += 1) {
        try testing.expectEqualSlices(u8, "\x00", r.rdata);
        const v = try rdata_mod.decodeTxt(r);
        try testing.expectEqual(@as(usize, 0), v.count());
    }
    try testing.expectEqual(@as(usize, 3), count);
    // Structurally invalid TXT bytes are refused and the builder is
    // unchanged (a length octet running past the rdata).
    const before = b.payloadLen();
    try testing.expectError(error.InvalidTxt, b.addRR(.answer, n, .txt, message.class_in, false, 4500, .{ .txt = "\x05ab" }));
    try testing.expectEqual(before, b.payloadLen());
    try testing.expectEqual(@as(usize, 3), b.recordCount());
    // `.raw` stays verbatim for callers that really want arbitrary bytes.
    try b.addRR(.answer, n, .txt, message.class_in, false, 4500, .{ .raw = "\x05ab" });
    try testing.expectEqual(@as(usize, 4), b.recordCount());
}

test "builder emits one RR when over MTU" {
    var buf: [hard_limit_v4]u8 = undefined;
    const big_txt: [2000]u8 = @splat(0); // 2000 empty strings
    const n = try Name.parse("big.local");
    // First record over the soft target is accepted.
    var b = Builder.init(&buf, .{ .family = .v4 });
    try b.addRR(.answer, n, .txt, message.class_in, false, 4500, .{ .txt = &big_txt });
    try testing.expect(b.payloadLen() > soft_limit_v4);
    try testing.expectEqual(@as(usize, 1), b.recordCount());
    // A second record, however small, does not fit any more.
    const before = b.payloadLen();
    try testing.expectError(error.NoSpace, b.addRR(.answer, n, .a, message.class_in, false, 120, .{ .a = .{ 1, 2, 3, 4 } }));
    try testing.expectEqual(before, b.payloadLen());
    try testing.expectEqual(@as(usize, 1), b.recordCount());
    const m = try Message.parse(b.finish());
    try testing.expectEqual(@as(u16, 1), m.header.ancount);
    // The other order: a small first record, then the oversize one, is
    // refused and leaves the builder unchanged.
    var c = Builder.init(&buf, .{ .family = .v4 });
    try c.addRR(.answer, n, .a, message.class_in, false, 120, .{ .a = .{ 1, 2, 3, 4 } });
    const small_len = c.payloadLen();
    const comp_before = c.comp_len;
    try testing.expectError(error.NoSpace, c.addRR(.answer, n, .txt, message.class_in, false, 4500, .{ .txt = &big_txt }));
    try testing.expectEqual(small_len, c.payloadLen());
    try testing.expectEqual(comp_before, c.comp_len);
    try testing.expectEqual(@as(u16, 1), (try Message.parse(c.finish())).header.ancount);
    // Records that fit under the soft target keep going.
    try c.addRR(.additional, n, .a, message.class_in, false, 120, .{ .a = .{ 1, 2, 3, 5 } });
    try testing.expectEqual(@as(usize, 2), c.recordCount());
}

test "builder payload never exceeds 8972 v4 or 8952 v6" {
    var buf: [9000]u8 = undefined;
    const n = try Name.parse("cap.local");
    const chunk: [1000]u8 = @splat(0);
    const big: [9000]u8 = @splat(0);
    for ([_]Family{ .v4, .v6 }) |family| {
        const cap = hardLimit(family);
        // A single record over the hard cap is refused.
        var b = Builder.init(&buf, .{ .family = family });
        try testing.expectError(error.NoSpace, b.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = &big }));
        try testing.expect(b.isEmpty());
        // A single record that lands exactly on the cap is accepted.
        const exact = cap - Header.len - n.len - 10;
        try b.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = big[0..exact] });
        try testing.expectEqual(cap, b.payloadLen());
        try testing.expectError(error.NoSpace, b.addRR(.answer, n, .a, message.class_in, false, 1, .{ .a = .{ 0, 0, 0, 0 } }));
        _ = try Message.parse(b.finish());
        // One octet more is refused.
        b.reset();
        try testing.expectError(error.NoSpace, b.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = big[0 .. exact + 1] }));
        try testing.expect(b.isEmpty());
        // Filling with mid-size records stops under the soft target.
        var c = Builder.init(&buf, .{ .family = family });
        var added: usize = 0;
        while (true) {
            c.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = &chunk }) catch |err| {
                try testing.expectEqual(error.NoSpace, err);
                break;
            };
            added += 1;
            try testing.expect(c.payloadLen() <= cap);
            try testing.expect(added < 100);
        }
        try testing.expect(c.payloadLen() <= softLimit(family));
        try testing.expectEqual(@as(usize, 1), added);
        const m = try Message.parse(c.finish());
        try testing.expectEqual(@as(u16, 1), m.header.ancount);
        // A smaller buffer lowers the hard cap.
        var small: [100]u8 = undefined;
        var d = Builder.init(&small, .{ .family = family });
        try testing.expectEqual(@as(usize, 100), d.hard_limit);
        try testing.expectEqual(@as(usize, 100), d.soft_limit);
        try testing.expectError(error.NoSpace, d.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = chunk[0..90] }));
        try d.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = chunk[0..67] });
        try testing.expectEqual(@as(usize, 100), d.payloadLen());
        // An `Options.hard_limit` (or `soft_limit`) override can lower the
        // cap but never lift it above the RFC 6762 section 17 payload cap.
        var e = Builder.init(&buf, .{ .family = family, .hard_limit = 9000, .soft_limit = 9000 });
        try testing.expectEqual(cap, e.hard_limit);
        try testing.expectEqual(cap, e.soft_limit);
        try testing.expectError(error.NoSpace, e.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = big[0 .. exact + 1] }));
        try testing.expect(e.isEmpty());
        try e.addRR(.answer, n, .txt, message.class_in, false, 1, .{ .txt = big[0..exact] });
        try testing.expectEqual(cap, e.payloadLen());
        const f = Builder.init(&buf, .{ .family = family, .hard_limit = 600 });
        try testing.expectEqual(@as(usize, 600), f.hard_limit);
    }
}

test "section order and question placement are enforced" {
    var buf: [512]u8 = undefined;
    var b = Builder.init(&buf, .{});
    const n = try Name.parse("x.local");
    try b.addRR(.authority, n, .a, message.class_in, false, 1, .{ .a = .{ 1, 1, 1, 1 } });
    try testing.expectError(error.SectionOrder, b.addRR(.answer, n, .a, message.class_in, false, 1, .{ .a = .{ 1, 1, 1, 1 } }));
    try testing.expectError(error.SectionOrder, b.addQuestion(n, .a, message.class_in, false));
    try b.addRR(.authority, n, .a, message.class_in, false, 1, .{ .a = .{ 1, 1, 1, 2 } });
    try b.addRR(.additional, n, .a, message.class_in, false, 1, .{ .a = .{ 1, 1, 1, 3 } });
    const m = try Message.parse(b.finish());
    try testing.expectEqual(@as(u16, 0), m.header.ancount);
    try testing.expectEqual(@as(u16, 2), m.header.nscount);
    try testing.expectEqual(@as(u16, 1), m.header.arcount);
    // Question too large for the soft limit leaves the builder unchanged.
    var tiny: [20]u8 = undefined;
    var t = Builder.init(&tiny, .{});
    try testing.expectError(error.NoSpace, t.addQuestion(n, .a, message.class_in, false));
    try testing.expect(t.isEmpty());
    try testing.expectEqual(@as(u16, 0), t.questionCount());
    // HINFO string bound.
    const long: [256]u8 = @splat('x');
    try testing.expectError(error.StringTooLong, b.addRR(.additional, n, .hinfo, message.class_in, false, 1, .{ .hinfo = .{ .cpu = &long, .os = "" } }));
}

test "compression matches exact bytes and reuses rdata names" {
    var buf: [512]u8 = undefined;
    var b = Builder.init(&buf, .{});
    const a = try Name.parse("Host.Local");
    const c = try Name.parse("svc._x._tcp.Local");
    try b.addRR(.answer, c, .ptr, message.class_in, false, 1, .{ .ptr = a });
    const after_first = b.payloadLen();
    // "Host.Local" now exists inside the PTR rdata; the owner of the next
    // record is a pointer only.
    try b.addRR(.answer, try Name.parse("Host.Local"), .a, message.class_in, false, 1, .{ .a = .{ 1, 2, 3, 4 } });
    try testing.expectEqual(after_first + 2 + 10 + 4, b.payloadLen());
    // A case variant is a different byte string: written in full, never
    // through a pointer to the other spelling, so what a peer decodes is
    // exactly what the caller passed (RFC 6762 section 8.2 compares the
    // uncompressed rdata octet by octet).
    const variant = try Name.parse("host.LOCAL");
    try b.addRR(.answer, variant, .a, message.class_in, false, 1, .{ .a = .{ 1, 2, 3, 5 } });
    try testing.expectEqual(after_first + (2 + 10 + 4) + (variant.len + 10 + 4), b.payloadLen());
    const pkt = b.finish();
    const m = try Message.parse(pkt);
    var an = m.answers();
    const r1 = an.next().?;
    // "Local" was compressed against the owner's "Local".
    try expectName("Host.Local", try rdata_mod.decodePtr(pkt, r1));
    const r2 = an.next().?;
    try expectName("Host.Local", r2.name);
    try testing.expectEqualSlices(u8, a.slice(), r2.name.slice());
    const r3 = an.next().?;
    try testing.expectEqualSlices(u8, variant.slice(), r3.name.slice());
    // The rdata name of the PTR shares the "Local" suffix with its owner.
    try testing.expect(r1.rdata.len < a.len);

    // The reviewer's case: owner "x.A" then a PTR to "a". The canonical
    // rdata must be the bytes given, not "A" through a pointer.
    var d = Builder.init(&buf, .{});
    const target = try Name.parse("a");
    try d.addRR(.answer, try Name.parse("x.A"), .ptr, message.class_in, false, 1, .{ .ptr = target });
    const pkt2 = d.finish();
    const m2 = try Message.parse(pkt2);
    var an2 = m2.answers();
    var canon: [64]u8 = undefined;
    try testing.expectEqualSlices(u8, target.slice(), try rdata_mod.canonicalRdata(pkt2, an2.next().?, &canon));
    // Same for an SRV target that differs only in case from the owner's
    // suffix: the decompressed rdata equals the flat encoding.
    var e = Builder.init(&buf, .{});
    const host = try Name.parse("Host.LOCAL");
    const srv: Srv = .{ .port = 1, .target = host };
    try e.addRR(.answer, try Name.parse("Alice._x._tcp.local"), .srv, message.class_in, false, 1, .{ .srv = srv });
    const pkt3 = e.finish();
    const m3 = try Message.parse(pkt3);
    var an3 = m3.answers();
    var flat: [300]u8 = undefined;
    const fl = try rdata_mod.encodeSrv(srv, &flat);
    try testing.expectEqualSlices(u8, flat[0..fl], try rdata_mod.canonicalRdata(pkt3, an3.next().?, &canon));
}

test "reset starts a new packet and keeps the id and flags" {
    var buf: [256]u8 = undefined;
    var b = Builder.init(&buf, .{});
    b.setId(7);
    b.setResponse();
    b.setTruncated(true);
    const n = try Name.parse("x.local");
    try b.addQuestion(n, .a, message.class_in, false);
    try b.addRR(.answer, n, .a, message.class_in, false, 1, .{ .a = .{ 1, 1, 1, 1 } });
    b.reset();
    try testing.expect(b.isEmpty());
    try b.addRR(.answer, n, .a, message.class_in, false, 1, .{ .a = .{ 1, 1, 1, 1 } });
    // After reset there is nothing to compress against: full name.
    try testing.expectEqual(Header.len + n.len + 10 + 4, b.payloadLen());
    const m = try Message.parse(b.finish());
    try testing.expectEqual(@as(u16, 7), m.header.id);
    try testing.expect(m.header.flags.tc and m.header.flags.qr);
    try testing.expectEqual(@as(u16, 0), m.header.qdcount);
    try testing.expectEqual(@as(u16, 1), m.header.ancount);
}

test "compression table overflow degrades to uncompressed names" {
    var buf: [hard_limit_v4]u8 = undefined;
    var b = Builder.init(&buf, .{ .soft_limit = hard_limit_v4 });
    var i: usize = 0;
    var label: [8]u8 = undefined;
    while (i < 200) : (i += 1) {
        const l = try std.fmt.bufPrint(&label, "n{d}", .{i});
        const n = try Name.fromLabels(&.{ l, "local" });
        try b.addRR(.answer, n, .a, message.class_in, false, 1, .{ .a = .{ 1, 1, 1, 1 } });
    }
    try testing.expectEqual(max_compression_entries, b.comp_len);
    const m = try Message.parse(b.finish());
    try testing.expectEqual(@as(u16, 200), m.header.ancount);
    var an = m.answers();
    var count: usize = 0;
    const local = try Name.parse("local");
    while (an.next()) |r| : (count += 1) {
        try testing.expect(r.name.endsWith(&local));
    }
    try testing.expectEqual(@as(usize, 200), count);
}
